import { folder } from 'leva'
import {
  InteractiveSurface, InstancedGrid,
  frostedGlass,
  holographicFoil,
  toonCel,
  wireframeMorph,
  moire,
  fractalZoom,
  liquidBlob,
  brushedMetal,
  neonLineArt,
  bioluminescent,
  xrayGhost,
  rainStreaks,
  scanlines,
  dither8bit,
  kineticType,
  plasma,
  voronoiCells,
  heatHaze,
  tunnelLayout,
  isometricStack,
  voxelSphere,
  voronoiShatter,
  gearField,
  kineticRing,
  origamiFold,
  waveGrid,
  galaxySpiral,
  cubeSwarm,
  CardFlip,
  MagneticGroup,
  SquashStretch,
  ElasticJiggle,
  PathSpline,
  MorphShape,
  ExplodedView,
  ParallaxLayers,
  OceanPlane,
  PortalRing,
  CameraFlythrough,
  PopupFold,
} from '@o3s/lib'
import type { GalleryEntry } from './registry'

/* AUTO-GENERATED effect entries (workflow-authored). Each surface uses the
   material's own controls; layouts get a count + the standalone components get
   a shared color/speed control set. Hand-tune individual entries as needed. */

export const generatedEntries: GalleryEntry[] = [
  { id:'frosted-glass', name:"Frosted Glass", family:'InteractiveSurface', category:'effects', difficulty:'easy',
    description:"Heavy frosted-glass blur with fake refraction wobble.",
    controls: (frostedGlass.controls ?? {}),
    render: (v) => <InteractiveSurface material={frostedGlass} params={v} /> },
  { id:'holographic-foil', name:"Holographic Foil", family:'InteractiveSurface', category:'effects', difficulty:'easy',
    description:"Rainbow foil sheen with a sharp specular streak.",
    controls: (holographicFoil.controls ?? {}),
    render: (v) => <InteractiveSurface material={holographicFoil} params={v} /> },
  { id:'toon-cel', name:"Toon Cel", family:'InteractiveSurface', category:'effects', difficulty:'easy',
    description:"Cel-shaded quantized lighting with a fresnel outline rim.",
    controls: (toonCel.controls ?? {}),
    render: (v) => <InteractiveSurface material={toonCel} params={v} /> },
  { id:'wireframe-morph', name:"Wireframe Morph", family:'InteractiveSurface', category:'effects', difficulty:'easy',
    description:"Grid lines morphing to solid fill over time/scroll.",
    controls: (wireframeMorph.controls ?? {}),
    render: (v) => <InteractiveSurface material={wireframeMorph} params={v} /> },
  { id:'moire', name:"Moiré", family:'InteractiveSurface', category:'effects', difficulty:'medium',
    description:"Two rotated line gratings producing moiré interference.",
    controls: (moire.controls ?? {}),
    render: (v) => <InteractiveSurface material={moire} params={v} /> },
  { id:'fractal-zoom', name:"Fractal Zoom", family:'InteractiveSurface', category:'effects', difficulty:'medium',
    description:"Animated escape-time fractal coloring; cursor pans.",
    controls: (fractalZoom.controls ?? {}),
    render: (v) => <InteractiveSurface material={fractalZoom} params={v} /> },
  { id:'liquid-blob', name:"Liquid Blob", family:'InteractiveSurface', category:'effects', difficulty:'medium',
    description:"Metaball blobs via smooth-min distance fields.",
    controls: (liquidBlob.controls ?? {}),
    render: (v) => <InteractiveSurface material={liquidBlob} params={v} /> },
  { id:'brushed-metal', name:"Brushed Metal", family:'InteractiveSurface', category:'effects', difficulty:'easy',
    description:"Anisotropic brushed-metal highlight streaks.",
    controls: (brushedMetal.controls ?? {}),
    render: (v) => <InteractiveSurface material={brushedMetal} params={v} /> },
  { id:'neon-line-art', name:"Neon Line Art", family:'InteractiveSurface', category:'effects', difficulty:'easy',
    description:"Emissive glowing line-art grid that pulses.",
    controls: (neonLineArt.controls ?? {}),
    render: (v) => <InteractiveSurface material={neonLineArt} params={v} /> },
  { id:'bioluminescent', name:"Bioluminescent", family:'InteractiveSurface', category:'effects', difficulty:'easy',
    description:"Dark surface with glowing organic cells that breathe.",
    controls: (bioluminescent.controls ?? {}),
    render: (v) => <InteractiveSurface material={bioluminescent} params={v} /> },
  { id:'xray-ghost', name:"X-Ray Ghost", family:'InteractiveSurface', category:'effects', difficulty:'easy',
    description:"Fresnel translucent edge-glow ghostly shading.",
    controls: (xrayGhost.controls ?? {}),
    render: (v) => <InteractiveSurface material={xrayGhost} params={v} /> },
  { id:'rain-streaks', name:"Rain Streaks", family:'InteractiveSurface', category:'effects', difficulty:'easy',
    description:"Vertical rain streaks with droplets running down glass.",
    controls: (rainStreaks.controls ?? {}),
    render: (v) => <InteractiveSurface material={rainStreaks} params={v} /> },
  { id:'scanlines', name:"Scanlines", family:'InteractiveSurface', category:'effects', difficulty:'easy',
    description:"CRT scanlines with chromatic offset and flicker.",
    controls: (scanlines.controls ?? {}),
    render: (v) => <InteractiveSurface material={scanlines} params={v} /> },
  { id:'dither8bit', name:"Dither 8-bit", family:'InteractiveSurface', category:'effects', difficulty:'easy',
    description:"Ordered-dither posterized retro shading.",
    controls: (dither8bit.controls ?? {}),
    render: (v) => <InteractiveSurface material={dither8bit} params={v} /> },
  { id:'kinetic-type', name:"Kinetic Type", family:'InteractiveSurface', category:'effects', difficulty:'easy',
    description:"Distortion field warping a procedural stripe pattern.",
    controls: (kineticType.controls ?? {}),
    render: (v) => <InteractiveSurface material={kineticType} params={v} /> },
  { id:'plasma', name:"Plasma", family:'InteractiveSurface', category:'effects', difficulty:'easy',
    description:"Classic demoscene plasma via summed sines.",
    controls: (plasma.controls ?? {}),
    render: (v) => <InteractiveSurface material={plasma} params={v} /> },
  { id:'voronoi-cells', name:"Voronoi Cells", family:'InteractiveSurface', category:'effects', difficulty:'medium',
    description:"Animated voronoi cells lit near the cursor.",
    controls: (voronoiCells.controls ?? {}),
    render: (v) => <InteractiveSurface material={voronoiCells} params={v} /> },
  { id:'heat-haze', name:"Heat Haze", family:'InteractiveSurface', category:'effects', difficulty:'medium',
    description:"Refractive heat-shimmer over a gradient backdrop.",
    controls: (heatHaze.controls ?? {}),
    render: (v) => <InteractiveSurface material={heatHaze} params={v} /> },
  { id:'tunnel-grid', name:"Infinite Tunnel", family:'InstancedGrid', category:'objects', difficulty:'medium',
    description:"Receding rings forming a tunnel scrolling toward camera.",
    controls: { count:{value:800,min:100,max:5000,step:100}, Instance: folder({ color:'#5fa8ff', metalness:{value:0.5,min:0,max:1,step:0.01}, roughness:{value:0.3,min:0,max:1,step:0.01} }) },
    render: (v) => <InstancedGrid layout={tunnelLayout({ count:(v.count as number) })} color={v.color as string} metalness={v.metalness as number} roughness={v.roughness as number} /> },
  { id:'isometric-stack-grid', name:"Isometric Stack", family:'InstancedGrid', category:'objects', difficulty:'medium',
    description:"Staggered cube grid with a Z-height ripple wave.",
    controls: { count:{value:800,min:100,max:5000,step:100}, Instance: folder({ color:'#5fa8ff', metalness:{value:0.5,min:0,max:1,step:0.01}, roughness:{value:0.3,min:0,max:1,step:0.01} }) },
    render: (v) => <InstancedGrid layout={isometricStack()} color={v.color as string} metalness={v.metalness as number} roughness={v.roughness as number} /> },
  { id:'voxel-sphere-grid', name:"Voxel Sphere", family:'InstancedGrid', category:'objects', difficulty:'medium',
    description:"Instances voxelizing a sphere surface; cursor displaces.",
    controls: { count:{value:800,min:100,max:5000,step:100}, Instance: folder({ color:'#5fa8ff', metalness:{value:0.5,min:0,max:1,step:0.01}, roughness:{value:0.3,min:0,max:1,step:0.01} }) },
    render: (v) => <InstancedGrid layout={voxelSphere({ count:(v.count as number) })} color={v.color as string} metalness={v.metalness as number} roughness={v.roughness as number} /> },
  { id:'voronoi-shatter-grid', name:"Voronoi Shatter", family:'InstancedGrid', category:'objects', difficulty:'medium',
    description:"Shards exploding outward and settling back, looping.",
    controls: { count:{value:800,min:100,max:5000,step:100}, Instance: folder({ color:'#5fa8ff', metalness:{value:0.5,min:0,max:1,step:0.01}, roughness:{value:0.3,min:0,max:1,step:0.01} }) },
    render: (v) => <InstancedGrid layout={voronoiShatter({ count:(v.count as number) })} color={v.color as string} metalness={v.metalness as number} roughness={v.roughness as number} /> },
  { id:'gear-field-grid', name:"Gear Field", family:'InstancedGrid', category:'objects', difficulty:'medium',
    description:"Grid of instances spinning like interlocking gears.",
    controls: { count:{value:800,min:100,max:5000,step:100}, Instance: folder({ color:'#5fa8ff', metalness:{value:0.5,min:0,max:1,step:0.01}, roughness:{value:0.3,min:0,max:1,step:0.01} }) },
    render: (v) => <InstancedGrid layout={gearField({ count:(v.count as number) })} color={v.color as string} metalness={v.metalness as number} roughness={v.roughness as number} /> },
  { id:'kinetic-ring-grid', name:"Kinetic Ring", family:'InstancedGrid', category:'objects', difficulty:'medium',
    description:"Instances on a tumbling ring facing outward.",
    controls: { count:{value:800,min:100,max:5000,step:100}, Instance: folder({ color:'#5fa8ff', metalness:{value:0.5,min:0,max:1,step:0.01}, roughness:{value:0.3,min:0,max:1,step:0.01} }) },
    render: (v) => <InstancedGrid layout={kineticRing({ count:(v.count as number) })} color={v.color as string} metalness={v.metalness as number} roughness={v.roughness as number} /> },
  { id:'origami-fold-grid', name:"Origami Fold", family:'InstancedGrid', category:'objects', difficulty:'medium',
    description:"Rows folding/unfolding accordion-style.",
    controls: { count:{value:800,min:100,max:5000,step:100}, Instance: folder({ color:'#5fa8ff', metalness:{value:0.5,min:0,max:1,step:0.01}, roughness:{value:0.3,min:0,max:1,step:0.01} }) },
    render: (v) => <InstancedGrid layout={origamiFold({ count:(v.count as number) })} color={v.color as string} metalness={v.metalness as number} roughness={v.roughness as number} /> },
  { id:'wave-grid-grid', name:"Wave Grid", family:'InstancedGrid', category:'objects', difficulty:'medium',
    description:"Flat grid with a traveling sine wave; cursor bumps it.",
    controls: { count:{value:800,min:100,max:5000,step:100}, Instance: folder({ color:'#5fa8ff', metalness:{value:0.5,min:0,max:1,step:0.01}, roughness:{value:0.3,min:0,max:1,step:0.01} }) },
    render: (v) => <InstancedGrid layout={waveGrid()} color={v.color as string} metalness={v.metalness as number} roughness={v.roughness as number} /> },
  { id:'galaxy-spiral-grid', name:"Galaxy Spiral", family:'InstancedGrid', category:'objects', difficulty:'medium',
    description:"Instances on logarithmic spiral arms rotating differentially.",
    controls: { count:{value:800,min:100,max:5000,step:100}, Instance: folder({ color:'#5fa8ff', metalness:{value:0.5,min:0,max:1,step:0.01}, roughness:{value:0.3,min:0,max:1,step:0.01} }) },
    render: (v) => <InstancedGrid layout={galaxySpiral({ count:(v.count as number) })} color={v.color as string} metalness={v.metalness as number} roughness={v.roughness as number} /> },
  { id:'cube-swarm-grid', name:"Cube Swarm", family:'InstancedGrid', category:'objects', difficulty:'medium',
    description:"Drifting bounded swarm with index-phase cohesion.",
    controls: { count:{value:800,min:100,max:5000,step:100}, Instance: folder({ color:'#5fa8ff', metalness:{value:0.5,min:0,max:1,step:0.01}, roughness:{value:0.3,min:0,max:1,step:0.01} }) },
    render: (v) => <InstancedGrid layout={cubeSwarm({ count:(v.count as number) })} color={v.color as string} metalness={v.metalness as number} roughness={v.roughness as number} /> },
  { id:'card-flip', name:"Card Flip", family:'FloatingObject', category:'objects', difficulty:'medium',
    description:"3D card that flips on hover with an idle tilt.",
    controls: { color:'#5fa8ff', speed:{value:1,min:0,max:4,step:0.1} },
    render: (v) => <CardFlip {...(v as any)} /> },
  { id:'magnetic-group', name:"Magnetic Group", family:'FloatingObject', category:'objects', difficulty:'medium',
    description:"Meshes that drift toward the cursor then ease back.",
    controls: { color:'#5fa8ff', speed:{value:1,min:0,max:4,step:0.1} },
    render: (v) => <MagneticGroup {...(v as any)} /> },
  { id:'squash-stretch', name:"Squash Stretch", family:'FloatingObject', category:'objects', difficulty:'medium',
    description:"Bouncing sphere with squash-and-stretch deformation.",
    controls: { color:'#5fa8ff', speed:{value:1,min:0,max:4,step:0.1} },
    render: (v) => <SquashStretch {...(v as any)} /> },
  { id:'elastic-jiggle', name:"Elastic Jiggle", family:'FloatingObject', category:'objects', difficulty:'medium',
    description:"Mesh that jiggles elastically when the cursor moves.",
    controls: { color:'#5fa8ff', speed:{value:1,min:0,max:4,step:0.1} },
    render: (v) => <ElasticJiggle {...(v as any)} /> },
  { id:'path-spline', name:"Path Spline", family:'FloatingObject', category:'objects', difficulty:'medium',
    description:"Mesh following a looping lissajous path with a ghost trail.",
    controls: { color:'#5fa8ff', speed:{value:1,min:0,max:4,step:0.1} },
    render: (v) => <PathSpline {...(v as any)} /> },
  { id:'morph-shape', name:"Morph Shape", family:'FloatingObject', category:'objects', difficulty:'medium',
    description:"Mesh morphing between sphere and box over time.",
    controls: { color:'#5fa8ff', speed:{value:1,min:0,max:4,step:0.1} },
    render: (v) => <MorphShape {...(v as any)} /> },
  { id:'exploded-view', name:"Exploded View", family:'ScrollScene', category:'website', difficulty:'medium',
    description:"Parts separating along Y as time rises (exploded view).",
    controls: { color:'#5fa8ff', speed:{value:1,min:0,max:4,step:0.1} },
    render: (v) => <ExplodedView {...(v as any)} /> },
  { id:'parallax-layers', name:"Parallax Layers", family:'ScrollScene', category:'website', difficulty:'medium',
    description:"Depth-layered planes that parallax with the cursor.",
    controls: { color:'#5fa8ff', speed:{value:1,min:0,max:4,step:0.1} },
    render: (v) => <ParallaxLayers {...(v as any)} /> },
  { id:'ocean-plane', name:"Ocean Plane", family:'ScrollScene', category:'website', difficulty:'medium',
    description:"Subdivided plane with Gerstner sine-wave displacement.",
    controls: { color:'#5fa8ff', speed:{value:1,min:0,max:4,step:0.1} },
    render: (v) => <OceanPlane {...(v as any)} /> },
  { id:'portal-ring', name:"Portal Ring", family:'ScrollScene', category:'website', difficulty:'medium',
    description:"Glowing torus portal with a swirling interior + particles.",
    controls: { color:'#5fa8ff', speed:{value:1,min:0,max:4,step:0.1} },
    render: (v) => <PortalRing {...(v as any)} /> },
  { id:'camera-flythrough', name:"Camera Flythrough", family:'ScrollScene', category:'website', difficulty:'medium',
    description:"Gates/rings drifting past the camera on a loop.",
    controls: { color:'#5fa8ff', speed:{value:1,min:0,max:4,step:0.1} },
    render: (v) => <CameraFlythrough {...(v as any)} /> },
  { id:'popup-fold', name:"Popup Fold", family:'ScrollScene', category:'website', difficulty:'medium',
    description:"Flat panels folding up into a 3D pop-up arrangement.",
    controls: { color:'#5fa8ff', speed:{value:1,min:0,max:4,step:0.1} },
    render: (v) => <PopupFold {...(v as any)} /> },
]
